---
# CodeRabbit Configuration
# This configuration reduces noise by focusing on critical issues and ignoring nitpicks
# Based on: https://docs.coderabbit.ai/reference/yaml-template

# Global settings
language: 'en-US'
tone_instructions: ''

reviews:
  # Use 'chill' profile to reduce nitpick comments and focus on important issues
  profile: 'chill'

  # Generate high-level summaries and walkthroughs
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'

  # Review status and commit status
  review_status: true
  commit_status: true
  fail_commit_status: false

  # Walkthrough settings
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true

  # Enable automatic reviews with incremental updates
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []

  # Configure tools to focus on important issues
  tools:
    # Essential linting tools
    eslint:
      enabled: true
      config_file: 'eslint.config.js'

    # TypeScript/JavaScript analysis
    biome:
      enabled: true

    # Security scanning
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    semgrep:
      enabled: true

    # Code quality tools
    ruff:
      enabled: true
    shellcheck:
      enabled: true
    yamllint:
      enabled: true

    # Documentation
    markdownlint:
      enabled: true

    # GitHub-specific
    github-checks:
      enabled: true
      timeout_ms: 90000

    # Language tools
    languagetool:
      enabled: true
      level: default

    # Additional tools for comprehensive analysis
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
    detekt:
      enabled: true
    flake8:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    phpmd:
      enabled: true
    phpcs:
      enabled: true
    cppcheck:
      enabled: true
    circleci:
      enabled: true
    clippy:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    pylint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
    luacheck:
      enabled: true
    brakeman:
      enabled: true
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true

  # Path filters - focus review on documentation and infrastructure
  path_filters:
  # Include specific paths for review
  - 'docs/**'
  - 'infrastructure/**'
  - '.coderabbit.yaml'
  - '.github/**'
  - 'eslint.config.js'
  - 'package.json'
  - 'pnpm-lock.yaml'
  - 'turbo.json'
  - 'tsconfig.json'
  - 'vitest.config.ts'
  - 'vitest.workspace.ts'
  - 'yaml-lint.config.js'

  # Exclude everything else (CodeRabbit will only review included paths)
  - '!**/*'
  # Pre-merge checks for quality gates
  pre_merge_checks:
    title:
      mode: 'warning'
      requirements: 'Use descriptive titles that explain the change'
    description:
      mode: 'warning'
      requirements: 'Include a brief description of changes'
    labels:
      mode: 'warning'
      requirements: 'Add appropriate labels for categorization'

  # Enable finishing touches for better code quality
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  # Chat and knowledge base integration
  chat:
    auto_reply: true
    integrations:
      jira:
        usage: auto
      linear:
        usage: auto

  # Knowledge base configuration
  knowledge_base:
    opt_out: false
    web_search:
      enabled: true
    code_guidelines:
      enabled: true
      filePatterns: []
    learnings:
      scope: auto
    issues:
      scope: auto
    jira:
      usage: auto
      project_keys: []
    linear:
      usage: auto
      team_keys: []
    pull_requests:
      scope: auto

  # Code generation settings
  code_generation:
    docstrings:
      language: en-US
      path_instructions:
      - path: ''
        instructions: ''
    unit_tests:
      path_instructions:
      - path: ''
        instructions: ''
