# Semgrep configuration for security scanning
# This file will be used when Semgrep is integrated via GitHub Actions

rules:
  # Custom rules for GitHub Actions workflows
  - id: github-actions-security
    languages: [yaml]
    message: 'GitHub Actions security rule'
    severity: ERROR
    patterns:
      - pattern: |
          uses: actions/checkout@v1
      - pattern: |
          uses: actions/setup-node@v1
      - pattern: |
          uses: actions/upload-artifact@v1
      - pattern: |
          uses: actions/download-artifact@v1

# Exclude certain paths
exclude:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'
  - '**/.next/**'
  - '**/out/**'
  - '**/tmp/**'
  - '**/.codeql/**'
  - '**/.tools/**'
