packages:
  - apps/*
  - packages/*
  - infrastructure
  - infrastructure/pulumi
  - tests/*

catalog:
  '@aws-sdk/client-auto-scaling': ^3.859.0
  '@aws-sdk/client-cloudwatch': ^3.859.0
  '@aws-sdk/client-cognito-identity-provider': ^3.859.0
  '@aws-sdk/client-dynamodb': ^3.859.0
  '@aws-sdk/client-ec2': ^3.859.0
  '@aws-sdk/client-elastic-load-balancing-v2': ^3.859.0
  '@aws-sdk/client-lambda': ^3.859.0
  '@aws-sdk/client-s3': ^3.859.0
  '@aws-sdk/client-sfn': ^3.859.0
  '@aws-sdk/client-ssm': ^3.859.0
  '@types/eslint': ^8
  '@types/express': ^5.0.3
  '@types/node': ^20.19.9
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@typescript-eslint/eslint-plugin': ^8.42.0
  '@typescript-eslint/parser': ^8.42.0
  '@typescript-eslint/utils': ^8.42.0
  typescript-eslint: ^8.42.0
  '@vitest/coverage-v8': 3.1.2
  '@vitest/ui': 3.1.2
  babel-plugin-react-compiler: 19.1.0-rc.2
  eslint: 9.35.0
  eslint-import-resolver-typescript: ^3.6.3
  eslint-plugin-oxlint: ^1.14.0
  eslint-plugin-unused-imports: ^4.2.0
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-testing-library: ^7.6.8
  eslint-plugin-security: ^3.0.1
  eslint-plugin-security-node: ^1.1.4
  eslint-plugin-no-secrets: ^2.2.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-array-func: ^5.0.2
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-sonarjs: ^3.0.5
  eslint-plugin-tailwindcss: ^3.18.2
  eslint-plugin-yml: ^1.18.0
  eslint-plugin-drizzle: ^0.2.3
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-refresh: ^0.4.20
  eslint-config-turbo: ^2.5.5
  eslint-config-flat-gitignore: ^2.1.0
  express: ^4.21.2
  globals: ^15.15.0
  lucide-react: ^0.474.0
  markdownlint-cli2: 0.18.1
  oxlint: ^0.15.0
  oxlint-tsgolint: ^0.2.0
  pino: ^9.7.0
  pino-pretty: ^11.3.0
  prettier: 3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwindcss: ^3.4.17
  tsx: ^4.20.3
  typescript: ^5.9.2
  vitest: 3.1.2
  zod: ^4.1.5
  zod-validation-error: ^4.0.2
