packages:
  - apps/*
  - packages/*

catalog:
  '@types/eslint': ^8
  '@types/express': ^4.17.21
  '@types/node': ^20
  '@typescript-eslint/eslint-plugin': ^7.8.0
  '@typescript-eslint/parser': ^7.8.0
  '@vitest/ui': 3.1.2
  eslint: ^9.25.1
  eslint-config-prettier: ^9.1.0
  eslint-plugin-import: ^2.29.1
  eslint-plugin-jsx-a11y: ^6.8.0
  eslint-plugin-react: ^7.34.1
  eslint-plugin-react-hooks: ^4.6.0
  eslint-plugin-unused-imports: ^3.1.0
  lucide-react: ^0.474.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.13
  typescript: ^5.6.3
  vitest: 3.1.2

  # Testing & Coverage
  '@vitest/coverage-v8': 3.1.2

  # Build & Development Tools
  tsx: ^4.19.4
  globals: ^15.15.0
  markdownlint-cli2: ^0.18.1

  # Core Dependencies
  zod: ^3.24.1
  'zod-validation-error': ^3.4.0
  pino: ^9.5.0
  'pino-pretty': ^11.3.0

  # AWS SDK
  '@aws-sdk/client-cognito-identity-provider': ^3.713.0
  '@aws-sdk/client-ssm': ^3.713.0

catalogs:
  react18:
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.0
    react: ^18.3.1
    react-dom: ^18.3.1
