packages:
  - apps/*
  - packages/*
  - infrastructure

catalog:
  '@aws-sdk/client-cognito-identity-provider': ^3.859.0
  '@aws-sdk/client-ssm': 3.859.0
  '@types/eslint': ^8
  '@types/express': ^5.0.3
  '@types/node': ^20.19.9
  '@typescript-eslint/eslint-plugin': ^8.31.1
  '@typescript-eslint/parser': ^8.31.1
  '@vitest/coverage-v8': 3.1.2
  '@vitest/ui': 3.1.2
  eslint: ^9.32.0
  eslint-config-prettier: ^9.1.2
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^4.6.2
  eslint-plugin-unused-imports: ^3.2.0
  globals: ^15.15.0
  lucide-react: ^0.474.0
  markdownlint-cli2: ^0.18.1
  pino: ^9.7.0
  pino-pretty: ^11.3.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  tsx: ^4.20.3
  typescript: ^5.9.2
  vitest: 3.1.2
  zod: ^3.25.76
  zod-validation-error: ^3.5.3

catalogs:
  react18:
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.0
    react: ^18.3.1
    react-dom: ^18.3.1
