packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^9.25.1
  prettier: ^3.3.3
  typescript: ^5.6.3
  '@types/node': ^20
  '@types/eslint': ^8
  # TypeScript ESLint
  '@typescript-eslint/eslint-plugin': ^7.8.0
  '@typescript-eslint/parser': ^7.8.0
  # Prettier integration
  eslint-config-prettier: ^9.1.0
  # Import/export linting
  eslint-plugin-import: ^2.29.1
  # React linting
  eslint-plugin-react: ^7.34.1
  eslint-plugin-react-hooks: ^4.6.0
  # JSX accessibility
  eslint-plugin-jsx-a11y: ^6.8.0
  # Unused imports (optional, but helpful)
  eslint-plugin-unused-imports: ^3.1.0

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.0
