name: Test workflow with very long line that should be allowed because workflow files have 200 character limit
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step with extremely long line that exceeds the default 120 character limit but should be fine for workflow files since they allow up to 200 characters for better readability in CI/CD configurations
        run: echo "This is a test to verify that workflow files use the correct line length limit"
