name: macro-ai-infrastructure
description: Macro-AI infrastructure managed with Pulumi
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
