name: 'Setup Environment'
description: 'Creates environment files for the project'

inputs:
  use_real_secrets:
    description: 'Whether to use real secrets from GitHub Secrets'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Create env files with real secrets
      if: inputs.use_real_secrets == 'true'
      shell: bash
      run: |
        # Create Express API .env file with real secrets
        mkdir -p apps/express-api
        cat > apps/express-api/.env << EOF
        # API Configuration
        API_KEY=${{ secrets.API_KEY }}
        SERVER_PORT=${{ secrets.SERVER_PORT || '3030' }}
        NODE_ENV=test

        # AWS Cognito Configuration
        AWS_COGNITO_REGION=${{ secrets.AWS_COGNITO_REGION || 'us-east-1' }}
        AWS_COGNITO_USER_POOL_ID=${{ secrets.AWS_COGNITO_USER_POOL_ID || 'dummy-pool-id' }}
        AWS_COGNITO_USER_POOL_CLIENT_ID=${{ secrets.AWS_COGNITO_USER_POOL_CLIENT_ID || 'dummy-client-id' }}
        AWS_COGNITO_USER_POOL_SECRET_KEY=${{ secrets.AWS_COGNITO_USER_POOL_SECRET_KEY || 'dummy-secret-key' }}
        AWS_COGNITO_ACCESS_KEY=${{ secrets.AWS_COGNITO_ACCESS_KEY || 'dummy-access-key' }}
        AWS_COGNITO_SECRET_KEY=${{ secrets.AWS_COGNITO_SECRET_KEY || 'dummy-secret-key' }}
        AWS_COGNITO_REFRESH_TOKEN_EXPIRY=${{ secrets.AWS_COGNITO_REFRESH_TOKEN_EXPIRY || '30' }}

        # Cookie Configuration
        COOKIE_DOMAIN=${{ secrets.COOKIE_DOMAIN || 'localhost' }}
        COOKIE_ENCRYPTION_KEY=${{ secrets.COOKIE_ENCRYPTION_KEY || 'dummy-encryption-key-at-least-32-chars-long' }}

        # Databases
        NON_RELATIONAL_DATABASE_URL=${{ secrets.NON_RELATIONAL_DATABASE_URL || 'dummy-url' }}
        RELATIONAL_DATABASE_URL=${{ secrets.RELATIONAL_DATABASE_URL || 'dummy-url' }}

        # Rate Limiting
        RATE_LIMIT_WINDOW_MS=${{ secrets.RATE_LIMIT_WINDOW_MS || '900000' }}
        RATE_LIMIT_MAX_REQUESTS=${{ secrets.RATE_LIMIT_MAX_REQUESTS || '100' }}
        AUTH_RATE_LIMIT_WINDOW_MS=${{ secrets.AUTH_RATE_LIMIT_WINDOW_MS || '3600000' }}
        AUTH_RATE_LIMIT_MAX_REQUESTS=${{ secrets.AUTH_RATE_LIMIT_MAX_REQUESTS || '10' }}
        API_RATE_LIMIT_WINDOW_MS=${{ secrets.API_RATE_LIMIT_WINDOW_MS || '60000' }}
        API_RATE_LIMIT_MAX_REQUESTS=${{ secrets.API_RATE_LIMIT_MAX_REQUESTS || '60' }}
        REDIS_URL=${{ secrets.REDIS_URL || 'redis://localhost:6379' }}
        EOF

        # Create Client UI .env file with real secrets
        mkdir -p apps/client-ui
        cat > apps/client-ui/.env << EOF
        VITE_API_URL=${{ secrets.VITE_API_URL || 'http://localhost:3030/api' }}
        VITE_API_KEY=${{ secrets.VITE_API_KEY || 'dummy-api-key-at-least-32-chars-long' }}
        EOF

    - name: Create env files with dummy values
      if: inputs.use_real_secrets != 'true'
      shell: bash
      run: |
        # Create Express API .env file with dummy values
        mkdir -p apps/express-api
        cat > apps/express-api/.env << EOF
        # API Configuration
        API_KEY=${{ github.event.repository.name }}-test-key-32chars-long-dummy
        SERVER_PORT=3030
        NODE_ENV=test

        # AWS Cognito Configuration
        AWS_COGNITO_REGION=us-east-1
        AWS_COGNITO_USER_POOL_ID=dummy-pool-id
        AWS_COGNITO_USER_POOL_CLIENT_ID=dummy-client-id
        AWS_COGNITO_USER_POOL_SECRET_KEY=dummy-secret-key
        AWS_COGNITO_ACCESS_KEY=dummy-access-key
        AWS_COGNITO_SECRET_KEY=dummy-secret-key
        AWS_COGNITO_REFRESH_TOKEN_EXPIRY=30

        # Cookie Configuration
        COOKIE_DOMAIN=localhost
        COOKIE_ENCRYPTION_KEY=dummy-encryption-key-at-least-32-chars-long

        # Databases
        NON_RELATIONAL_DATABASE_URL=dummy-url
        RELATIONAL_DATABASE_URL=dummy-url

        # Rate Limiting
        RATE_LIMIT_WINDOW_MS=900000
        RATE_LIMIT_MAX_REQUESTS=100
        AUTH_RATE_LIMIT_WINDOW_MS=3600000
        AUTH_RATE_LIMIT_MAX_REQUESTS=10
        API_RATE_LIMIT_WINDOW_MS=60000
        API_RATE_LIMIT_MAX_REQUESTS=60
        REDIS_URL=redis://localhost:6379
        EOF

        # Create Client UI .env file with dummy values
        mkdir -p apps/client-ui
        cat > apps/client-ui/.env << EOF
        VITE_API_URL=http://localhost:3030/api
        VITE_API_KEY=dummy-api-key-at-least-32-chars-long
        EOF
