name: Comprehensive Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
  # Run comprehensive security scan daily at 2 AM UTC
  - cron: '0 2 * * *'

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for better analysis

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.14.0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    # ESLint Security Scanning
    - name: Run ESLint Security Scan
      run: pnpm lint:eslint
      env:
        # Mock environment variables for API client generation
        API_KEY: 'mock-api-key-for-ci-testing-purposes-only-32-chars-min'
        NODE_ENV: 'test'
        APP_ENV: 'test'
        SERVER_PORT: '3040'
        AWS_COGNITO_REGION: 'us-east-1'
        AWS_COGNITO_USER_POOL_ID: 'mock-user-pool-id'
        AWS_COGNITO_USER_POOL_CLIENT_ID: 'mock-client-id'
        AWS_COGNITO_REFRESH_TOKEN_EXPIRY: '30'
        COOKIE_DOMAIN: 'localhost'
        COOKIE_ENCRYPTION_KEY: 'mock-cookie-encryption-key-32-chars-minimum'
        REDIS_URL: 'redis://localhost:6379'
        RELATIONAL_DATABASE_URL: 'postgresql://localhost:5432/test_db'
        OPENAI_API_KEY: 'sk-mock-openai-key-for-ci-testing'
        RATE_LIMIT_WINDOW_MS: '900000'
        RATE_LIMIT_MAX_REQUESTS: '100'
        AUTH_RATE_LIMIT_WINDOW_MS: '3600000'
        AUTH_RATE_LIMIT_MAX_REQUESTS: '10'
        API_RATE_LIMIT_WINDOW_MS: '60000'
        API_RATE_LIMIT_MAX_REQUESTS: '60'

    # Snyk Security Scanning
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    # Semgrep Security Scanning
    - name: Run Semgrep Security Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security p/owasp-top-ten p/javascript p/typescript p/yaml p/github-actions .semgrep.yml
        generateSarif: '0'
        generateGitlab: '0'
        generateGithub: '1'

    # GitHub Actions Workflow Security Scanning
    - name: Run Actionlint
      uses: reviewdog/action-actionlint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-check
        filter_mode: diff_context
        fail_on_error: true

    # Dependency Audit
    - name: Run npm audit
      run: pnpm audit --audit-level moderate
      continue-on-error: true

    # Check for secrets
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
